# Generated by Django 4.2.14 on 2024-07-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_id',
            field=models.PositiveBigIntegerField(db_index=True, unique=True),
        ),
    ]
